/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.RunPackage.view;
import TestTool.model.RunPackage.*;
import TestTool.model.RunPackage.model.StudentRun;
import TestTool.model.TestPackage.model.Test;
import TestTool.model.TestPackage.view.JFrameTestInfo;
import TestTool.model.UserPackage.Student;
import TestTool.view.WindowPackage.JFrameLogin;
import java.util.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dung Trinh
 */
public class JFrameStudentHome extends javax.swing.JFrame {
    
    
    private int testIndex;

    //Should return the student;
    Student student;
    private StudentRun studentRun; 
    public DefaultTableModel model;
    public DefaultTableModel testInfo;
    
    
    private ArrayList<Test> takenTests, availableTests;
    /**
     * Creates new form JFrameStudentHome
     */
    public JFrameStudentHome(StudentRun studentRun) 
    {   
        this.studentRun = studentRun; 
        //now got the student. Can work on student
        student = studentRun.getStudent();
        
        this.takenTests = studentRun.getCompleteTest();
        this.availableTests = studentRun.getAvailableTest();
        this.testIndex = 0;
        model = new DefaultTableModel();
        
        model.addColumn("Test");
        model.addColumn("Status");
        model.addColumn("Grade");
        
        for (int i = 0; i < takenTests.size(); i++) {
            model.addRow(new Object[] {takenTests.get(i).getTestName(), 
                                        "Complete",takenTests.get(i).getPoint()});
        }
        

        initComponents();
        jLabelStudentHome.setText(student.getName());
        
        //Set the model for the GUI table
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStudentHome = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelAvailableTests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSelectedTests = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAvailableTests = new javax.swing.JList();
        jButtonTakeTest = new javax.swing.JButton();
        jLabelSelectedTests = new javax.swing.JLabel();
        jLabelTakenTests = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTakenTests = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Student Home");

        jLabelStudentHome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelStudentHome.setText("Student Home");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelAvailableTests.setText("Available Tests");

        jTableSelectedTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableSelectedTests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSelectedTestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSelectedTests);

        jListAvailableTests.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAvailableTestsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListAvailableTests);

        jButtonTakeTest.setText("Take Test");
        jButtonTakeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeTestActionPerformed(evt);
            }
        });

        jLabelSelectedTests.setText("Selected Test");

        jLabelTakenTests.setText("Taken Tests");

        jTableTakenTests.setModel(model);
        jScrollPane3.setViewportView(jTableTakenTests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonTakeTest, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAvailableTests)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStudentHome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jButtonLogout))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSelectedTests)
                        .addComponent(jLabelTakenTests)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jLabelStudentHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvailableTests)
                    .addComponent(jLabelSelectedTests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabelTakenTests)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonTakeTest)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        System.out.println("Call JFrameLogin");
        
        //Should update the student info 
        System.out.print("Update the info for the library");
        JFrameLogin newJFrameLogin = new JFrameLogin();
        newJFrameLogin.setVisible(true);
        this.setVisible(false);
        
        //copy data of student back to data base
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonTakeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeTestActionPerformed
        //the index is from student home window
        //get from list listener
        JFrameTestInfo newJFrameTestInfo = new JFrameTestInfo(this.studentRun,this.testIndex);
        newJFrameTestInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTakeTestActionPerformed

    
    private void jListAvailableTestsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAvailableTestsValueChanged
        //System.out.println("Print index");
        
        //Return the index of clicking on list
        //why is this become -1
        System.out.println("in here " + jListAvailableTests.getAnchorSelectionIndex());
        this.testIndex = jListAvailableTests.getAnchorSelectionIndex();
        
        testInfo = new DefaultTableModel();
        testInfo.addColumn("Instructor");
        testInfo.addColumn("Type");
        testInfo.addColumn("Time");
        testInfo.addColumn("Difficulty");
        testInfo.addColumn("Due Date");
        
        //change something in date
        testInfo.addRow(new Object[] {availableTests.get(testIndex).getInstructor(), 
                   "In class",availableTests.get(testIndex).getTestTime(),
                   availableTests.get(testIndex).getDifficulty(),
                    "Date"});
        
        jTableSelectedTests.setModel(testInfo);

    }//GEN-LAST:event_jListAvailableTestsValueChanged
    
    
    //No need to use
    private void jTableSelectedTestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSelectedTestsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSelectedTestsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameStudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameStudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameStudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameStudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameStudentHome(new StudentRun("student")).setVisible(true);
            }
        });
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTakeTest;
    private javax.swing.JLabel jLabelAvailableTests;
    private javax.swing.JLabel jLabelSelectedTests;
    private javax.swing.JLabel jLabelStudentHome;
    private javax.swing.JLabel jLabelTakenTests;
    private javax.swing.JList jListAvailableTests;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableSelectedTests;
    private javax.swing.JTable jTableTakenTests;
    // End of variables declaration//GEN-END:variables
}
