/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.RunPackage.view;

import TestTool.model.QuestionPackage.view.JFrameQuestionBank;
import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.TestPackage.model.GenerateTest;
import TestTool.model.TestPackage.model.Test;
import TestTool.model.TestPackage.model.TestBank;
import TestTool.model.TestPackage.view.JFrameCreateTest;
import TestTool.model.TestPackage.view.JFrameEditTest;
import TestTool.model.TestPackage.view.JFrameGradeQuestionBank;
import TestTool.model.TestPackage.view.JFramePublishTest;
import TestTool.model.UserPackage.Teacher;
import TestTool.view.WindowPackage.JFrameLogin;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zach
 */
public class JFrameTeacherHome extends javax.swing.JFrame {

    private Teacher teacher;
    private Test test;
    private TeacherRun teacherRun;
    private JTable table;
    private DefaultTableModel model;
    private TestBank tBank;
    
    /**
     * Creates new form teacherOverview
     */
    public JFrameTeacherHome() {
        initComponents();
    }
    
    public JFrameTeacherHome(TeacherRun teacherRun) {
        this.teacherRun = teacherRun;
        teacher = teacherRun.getTeacher();
        tBank = new TestBank();
        ArrayList<Test> tests = tBank.fillTests();
        initComponents();
        model = (DefaultTableModel) jTableTests.getModel();
        
        for (int i=0; i<tests.size(); i++) {
            Test cur = tests.get(i);
            if (!cur.isPublished()) {
                Object[] row = {
                    cur.getTestName(),
                    cur.isGraded(),
                    cur.getDateCreated(),
                    cur.getDateDue(),
                };
                model.addRow(row);
            }
            else {
                System.out.println(cur.getTestName() + " is published.");
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();
        jScrollPaneTests = new javax.swing.JScrollPane();
        jTableTests = new javax.swing.JTable();
        jButtonEditTest = new javax.swing.JButton();
        jButtonCreateTest = new javax.swing.JButton();
        jButtonPublishTest = new javax.swing.JButton();
        jButtonQuestionBank = new javax.swing.JButton();
        jButtonGradeTest = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Test Bank");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelWelcome.setText("Welcome");

        jTableTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test", "Graded", "Created Date", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTests.setViewportView(jTableTests);

        jButtonEditTest.setText("Edit Test");
        jButtonEditTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTestActionPerformed(evt);
            }
        });

        jButtonCreateTest.setText("Create Test");
        jButtonCreateTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateTestActionPerformed(evt);
            }
        });

        jButtonPublishTest.setText("Publish Test");
        jButtonPublishTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublishTestActionPerformed(evt);
            }
        });

        jButtonQuestionBank.setText("Question Bank");
        jButtonQuestionBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestionBankActionPerformed(evt);
            }
        });

        jButtonGradeTest.setText("Grade Test");
        jButtonGradeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGradeTestActionPerformed(evt);
            }
        });

        jTextField1.setText(teacher.getUserID());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPaneTests, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButtonEditTest)
                                .addGap(70, 70, 70)
                                .addComponent(jButtonCreateTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPublishTest)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButtonQuestionBank)
                .addGap(72, 72, 72)
                .addComponent(jButtonGradeTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelWelcome)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTests, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditTest)
                    .addComponent(jButtonCreateTest)
                    .addComponent(jButtonPublishTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuestionBank)
                    .addComponent(jButtonGradeTest))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        JFrameLogin newJFrameLogin = new JFrameLogin();
        newJFrameLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonCreateTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateTestActionPerformed
        
        JFrameCreateTest createWindow = new JFrameCreateTest(teacherRun);
        createWindow.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateTestActionPerformed

    private void jButtonEditTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTestActionPerformed
        test = teacher.getTests().get(jTableTests.getSelectedRow());
        JFrameEditTest editTestWindow = new JFrameEditTest(teacherRun, test);
        editTestWindow.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditTestActionPerformed

    private void jButtonPublishTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublishTestActionPerformed
        test = teacher.getTests().get(jTableTests.getSelectedRow());
        JFramePublishTest publishTestWindow = new JFramePublishTest(teacherRun, test);
        publishTestWindow.setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPublishTestActionPerformed

    private void jButtonGradeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGradeTestActionPerformed
        test = teacher.getTests().get(jTableTests.getSelectedRow());
        JFrameGradeQuestionBank gradeQuestionBankWindow = new JFrameGradeQuestionBank(teacherRun, test);
        gradeQuestionBankWindow.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGradeTestActionPerformed

    private void jButtonQuestionBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionBankActionPerformed
        JFrameQuestionBank questionBankWindow = new JFrameQuestionBank(teacherRun);
        questionBankWindow.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuestionBankActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTeacherHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTeacherHome(new TeacherRun("")).setVisible(true);
            }
        });
    }

    public JTable getTable() {
        return jTableTests;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateTest;
    private javax.swing.JButton jButtonEditTest;
    private javax.swing.JButton jButtonGradeTest;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPublishTest;
    private javax.swing.JButton jButtonQuestionBank;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JScrollPane jScrollPaneTests;
    private javax.swing.JTable jTableTests;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
