/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.QuestionPackage.view.JFrameCreateQuestion;
import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.RunPackage.view.JFrameTeacherHome;
import TestTool.model.TestPackage.model.GenerateTest;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Zach
 */
public class JFrameCreateTestQuestionBank extends JFrame {

    TeacherRun teacherRun;
    GenerateTest generateTest;
    /**
     * Creates new form JFrameCreateTestQuestionBank
     */
    public JFrameCreateTestQuestionBank(TeacherRun teacherRun, 
            GenerateTest generateTest) {
        this.teacherRun = teacherRun;
        this.generateTest = generateTest;
        initComponents();
    }
    
    /*for the main to run, nothing will work though*/
    public JFrameCreateTestQuestionBank() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCreateTest = new javax.swing.JLabel();
        jLabelQuestionBank = new javax.swing.JLabel();
        jLabelSort = new javax.swing.JLabel();
        jComboBoxSort = new javax.swing.JComboBox();
        jScrollPaneQuestion = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jButtonCreateQuestion = new javax.swing.JButton();
        jLabelAverageDifficulty = new javax.swing.JLabel();
        jTextFieldAverageDifficulty = new javax.swing.JTextField();
        jLabelTotalPoints = new javax.swing.JLabel();
        jTextFieldTotalPoints = new javax.swing.JTextField();
        jLabelTotalTime = new javax.swing.JLabel();
        jTextFieldTotalTime = new javax.swing.JTextField();
        jLabelQuestions = new javax.swing.JLabel();
        jTextFieldQuestions = new javax.swing.JTextField();
        jToggleButtonBack = new javax.swing.JToggleButton();
        jToggleButtonSaveTest = new javax.swing.JToggleButton();
        jButtonMoveQuestionUp = new javax.swing.JButton();
        jButtonMoveQuestionDown = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Create Test");

        jLabelCreateTest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCreateTest.setText("Create Test");

        jLabelQuestionBank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelQuestionBank.setText("Question Bank:");

        jLabelSort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSort.setText("Sort:");

        jComboBoxSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Difficulty", "Type", "Date", "Time", "Points" }));

        jTableQuestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "View/Edit", "Use", "Question", "ID", "Type", "Difficulty", "Time", "Points"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneQuestion.setViewportView(jTableQuestions);
        if (jTableQuestions.getColumnModel().getColumnCount() > 0) {
            jTableQuestions.getColumnModel().getColumn(1).setResizable(false);
            jTableQuestions.getColumnModel().getColumn(1).setPreferredWidth(35);
            jTableQuestions.getColumnModel().getColumn(3).setPreferredWidth(35);
        }

        jButtonCreateQuestion.setText("Create Question");
        jButtonCreateQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateQuestionActionPerformed(evt);
            }
        });

        jLabelAverageDifficulty.setText("Average Difficulty:");

        jTextFieldAverageDifficulty.setEditable(false);
        jTextFieldAverageDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAverageDifficultyActionPerformed(evt);
            }
        });

        jLabelTotalPoints.setText("Total Points:");

        jTextFieldTotalPoints.setEditable(false);
        jTextFieldTotalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalPointsActionPerformed(evt);
            }
        });

        jLabelTotalTime.setText("Total Time:");

        jTextFieldTotalTime.setEditable(false);
        jTextFieldTotalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTimeActionPerformed(evt);
            }
        });

        jLabelQuestions.setText("Questions:");

        jTextFieldQuestions.setEditable(false);
        jTextFieldQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuestionsActionPerformed(evt);
            }
        });

        jToggleButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonBack.setText("Back");
        jToggleButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBackActionPerformed(evt);
            }
        });

        jToggleButtonSaveTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonSaveTest.setText("Save Test");
        jToggleButtonSaveTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSaveTestActionPerformed(evt);
            }
        });

        jButtonMoveQuestionUp.setText("Move Question Up");
        jButtonMoveQuestionUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveQuestionUpActionPerformed(evt);
            }
        });

        jButtonMoveQuestionDown.setText("Move Question Down");
        jButtonMoveQuestionDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveQuestionDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMoveQuestionUp)
                        .addGap(69, 69, 69)
                        .addComponent(jButtonMoveQuestionDown))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelQuestionBank)
                            .addGap(100, 100, 100)
                            .addComponent(jLabelSort)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreateQuestion))
                        .addComponent(jScrollPaneQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAverageDifficulty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabelTotalPoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotalTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonBack)
                                .addGap(120, 120, 120)
                                .addComponent(jToggleButtonSaveTest)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCreateTest)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCreateTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestionBank)
                    .addComponent(jLabelSort)
                    .addComponent(jComboBoxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMoveQuestionUp)
                    .addComponent(jButtonMoveQuestionDown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAverageDifficulty)
                    .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalPoints)
                    .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalTime)
                    .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuestions)
                    .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonBack)
                    .addComponent(jToggleButtonSaveTest))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateQuestionActionPerformed
        JFrameCreateQuestion createQuestionWindow = new JFrameCreateQuestion(teacherRun);
        createQuestionWindow.setVisible(true);
        this.setVisible(false);               // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateQuestionActionPerformed

    private void jTextFieldAverageDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAverageDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAverageDifficultyActionPerformed

    private void jTextFieldTotalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalPointsActionPerformed

    private void jTextFieldTotalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTimeActionPerformed

    private void jTextFieldQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuestionsActionPerformed

    private void jToggleButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBackActionPerformed
        JFrameCreateTest createWindow = new JFrameCreateTest(teacherRun);
        createWindow.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonBackActionPerformed

    private void jToggleButtonSaveTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSaveTestActionPerformed
        generateTest.saveTest();
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonSaveTestActionPerformed

    private void jButtonMoveQuestionUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveQuestionUpActionPerformed
        generateTest.moveUp(jTableQuestions.getSelectedRow());
    }//GEN-LAST:event_jButtonMoveQuestionUpActionPerformed

    private void jButtonMoveQuestionDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveQuestionDownActionPerformed
        generateTest.moveDown(jTableQuestions.getSelectedRow());
    }//GEN-LAST:event_jButtonMoveQuestionDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTestQuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTestQuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTestQuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTestQuestionBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCreateTestQuestionBank().setVisible(true);
            }
        });
    }
    
    public JTable getQuestionTable() {
        return this.jTableQuestions;
    }
    
    public JTextField getAverageDifficulty() {
        return jTextFieldAverageDifficulty;
    }
    
    public JTextField getTotalPoints() {
        return jTextFieldTotalPoints;
    }
    
    public JTextField getTotalTime() {
        return jTextFieldTotalTime;
    }
    
    public JTextField getNumQuestionsLabel() {
        return jTextFieldQuestions;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateQuestion;
    private javax.swing.JButton jButtonMoveQuestionDown;
    private javax.swing.JButton jButtonMoveQuestionUp;
    private javax.swing.JComboBox jComboBoxSort;
    private javax.swing.JLabel jLabelAverageDifficulty;
    private javax.swing.JLabel jLabelCreateTest;
    private javax.swing.JLabel jLabelQuestionBank;
    private javax.swing.JLabel jLabelQuestions;
    private javax.swing.JLabel jLabelSort;
    private javax.swing.JLabel jLabelTotalPoints;
    private javax.swing.JLabel jLabelTotalTime;
    private javax.swing.JScrollPane jScrollPaneQuestion;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTextField jTextFieldAverageDifficulty;
    private javax.swing.JTextField jTextFieldQuestions;
    private javax.swing.JTextField jTextFieldTotalPoints;
    private javax.swing.JTextField jTextFieldTotalTime;
    private javax.swing.JToggleButton jToggleButtonBack;
    private javax.swing.JToggleButton jToggleButtonSaveTest;
    // End of variables declaration//GEN-END:variables
}
