/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;
import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.RunPackage.view.JFrameTeacherHome;
import TestTool.model.TestPackage.model.GenerateTest;
import TestTool.model.UserPackage.Teacher;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Zach
 */
public class JFrameCreateTest extends javax.swing.JFrame {
    
    TeacherRun teacher;
    /**
     * Creates new form CreateTest
     */
    
    public JFrameCreateTest() {

        initComponents();
    }
    
    public JFrameCreateTest(TeacherRun teacher) {
        
        this.teacher = teacher;
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCreateTest = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelTestType = new javax.swing.JLabel();
        jLabelTimer = new javax.swing.JLabel();
        jComboBoxClass = new javax.swing.JComboBox();
        jComboBoxTestType = new javax.swing.JComboBox();
        jLabelHour = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jTextFieldHour = new javax.swing.JTextField();
        jTextFieldMinutes = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jLabelTestName = new javax.swing.JLabel();
        jTextFieldTestName = new javax.swing.JTextField();
        jButtonAutoGenerate = new javax.swing.JButton();
        jButtonManuallyGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Create Test");

        jLabelCreateTest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCreateTest.setText("Create Test");

        jLabelClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClass.setText("Class:");

        jLabelTestType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTestType.setText("Test Type:");

        jLabelTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTimer.setText("Timer:");

        jComboBoxClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPE 307", "CPE 101", "CPE 102", "CPE 103" }));
        jComboBoxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClassActionPerformed(evt);
            }
        });

        jComboBoxTestType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Take Home", "Practice", "Proctored" }));

        jLabelHour.setText("Hr");

        jLabelMinutes.setText("Min");

        jTextFieldHour.setText("0");
        jTextFieldHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourActionPerformed(evt);
            }
        });

        jTextFieldMinutes.setText("0");

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelTestName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTestName.setText("Test Name:");

        jTextFieldTestName.setText("Midterm 1");
        jTextFieldTestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestNameActionPerformed(evt);
            }
        });

        jButtonAutoGenerate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAutoGenerate.setText("Auto-Generate");
        jButtonAutoGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoGenerateActionPerformed(evt);
            }
        });

        jButtonManuallyGenerate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonManuallyGenerate.setText("Manually Generate");
        jButtonManuallyGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManuallyGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClass)
                            .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTestType)
                            .addComponent(jComboBoxTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldHour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelHour)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMinutes))
                            .addComponent(jLabelTimer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCreateTest)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTestName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAutoGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManuallyGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCreateTest)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClass)
                    .addComponent(jLabelTestType)
                    .addComponent(jLabelTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHour)
                    .addComponent(jLabelMinutes)
                    .addComponent(jTextFieldHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTestName)
                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAutoGenerate)
                    .addComponent(jButtonManuallyGenerate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClassActionPerformed

    private void jTextFieldHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        /*could use teacherHome instead of creating new home*/
        
        teacher.resetWindow();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldTestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestNameActionPerformed

    private void jButtonAutoGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoGenerateActionPerformed
        JFrameAutoGenerate autoGenerateWindow = new JFrameAutoGenerate(teacher, this);
        autoGenerateWindow.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutoGenerateActionPerformed

    private void jButtonManuallyGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManuallyGenerateActionPerformed
        new GenerateTest(teacher, this);
        this.setVisible(false);    // TODO add your handling code here:*/
    }//GEN-LAST:event_jButtonManuallyGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCreateTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCreateTest(new TeacherRun(""))
                        .setVisible(true);
            }
        });
    }

    public JTextField getTestName() {
        return jTextFieldTestName;
    }
    
    public JComboBox getClassName() {
        return jComboBoxClass;
    }
    
    public JComboBox getTestType() {
        return jComboBoxTestType;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutoGenerate;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonManuallyGenerate;
    private javax.swing.JComboBox jComboBoxClass;
    private javax.swing.JComboBox jComboBoxTestType;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelCreateTest;
    private javax.swing.JLabel jLabelHour;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelTestName;
    private javax.swing.JLabel jLabelTestType;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JTextField jTextFieldHour;
    private javax.swing.JTextField jTextFieldMinutes;
    private javax.swing.JTextField jTextFieldTestName;
    // End of variables declaration//GEN-END:variables
}
