/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.RunPackage.view.JFrameTeacherHome;
import TestTool.model.TestPackage.model.Test;

/**
 *
 * @author Zach
 */
public class JFramePublishTest extends javax.swing.JFrame {

    TeacherRun teacherRun;
    Test test;
    /**
     * Creates new form JFramePublishTest
     */
    public JFramePublishTest(TeacherRun teacherRun, Test test) {
        this.teacherRun = teacherRun;
        this.test = test;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTestType = new javax.swing.JLabel();
        jLabelTimer = new javax.swing.JLabel();
        jLabelTotalPoints = new javax.swing.JLabel();
        jTextFieldTotalPoints = new javax.swing.JTextField();
        jLabelHour = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jLabelTotalTime = new javax.swing.JLabel();
        jTextFieldHour = new javax.swing.JTextField();
        jTextFieldMinutes = new javax.swing.JTextField();
        jTextFieldTotalTime = new javax.swing.JTextField();
        jLabelClass = new javax.swing.JLabel();
        jLabelQuestions = new javax.swing.JLabel();
        jLabelTestName = new javax.swing.JLabel();
        jTextFieldTestName = new javax.swing.JTextField();
        jTextFieldQuestions = new javax.swing.JTextField();
        jToggleButtonCancel = new javax.swing.JToggleButton();
        jToggleButtonPublish = new javax.swing.JToggleButton();
        jLabelAverageDifficulty = new javax.swing.JLabel();
        jTextFieldAverageDifficulty = new javax.swing.JTextField();
        jTextFieldClass = new javax.swing.JTextField();
        jTextFieldTestType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Publish Test");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Publish Test");

        jLabelTestType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTestType.setText("Test Type:");

        jLabelTimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTimer.setText("Timer:");

        jLabelTotalPoints.setText("Total Points:");

        jTextFieldTotalPoints.setEditable(false);
        jTextFieldTotalPoints.setText(test.getPoint() + "");
        jTextFieldTotalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalPointsActionPerformed(evt);
            }
        });

        jLabelHour.setText("Hr");

        jLabelMinutes.setText("Min");

        jLabelTotalTime.setText("Expected Time:");

        jTextFieldHour.setEditable(false);
        jTextFieldHour.setText("2");
        jTextFieldHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHourActionPerformed(evt);
            }
        });

        jTextFieldMinutes.setEditable(false);
        jTextFieldMinutes.setText("0");

        jTextFieldTotalTime.setEditable(false);
        jTextFieldTotalTime.setText(test.getTestTime() + "");
        jTextFieldTotalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTimeActionPerformed(evt);
            }
        });

        jLabelClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelClass.setText("Class:");

        jLabelQuestions.setText("Questions:");

        jLabelTestName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTestName.setText("Test Name:");

        jTextFieldTestName.setEditable(false);
        jTextFieldTestName.setText(test.getTestName());

        jTextFieldQuestions.setEditable(false);
        jTextFieldQuestions.setText(test.size() + "");
        jTextFieldQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuestionsActionPerformed(evt);
            }
        });

        jToggleButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonCancel.setText("Cancel");
        jToggleButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelActionPerformed(evt);
            }
        });

        jToggleButtonPublish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonPublish.setText("Publish");
        jToggleButtonPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPublishActionPerformed(evt);
            }
        });

        jLabelAverageDifficulty.setText("Average Difficulty:");

        jTextFieldAverageDifficulty.setEditable(false);
        jTextFieldAverageDifficulty.setText(test.getDifficulty() + "");
        jTextFieldAverageDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAverageDifficultyActionPerformed(evt);
            }
        });

        jTextFieldClass.setEditable(false);
        jTextFieldClass.setText(test.getClassname());
        jTextFieldClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClassActionPerformed(evt);
            }
        });

        jTextFieldTestType.setEditable(false);
        jTextFieldTestType.setText("Take Home");
        jTextFieldTestType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTestName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonCancel)
                        .addGap(94, 94, 94)
                        .addComponent(jToggleButtonPublish))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTestType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHour)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMinutes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelAverageDifficulty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotalPoints)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelTotalTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTestName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAverageDifficulty)
                    .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalPoints)
                    .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalTime)
                    .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuestions)
                    .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClass)
                    .addComponent(jLabelTestType)
                    .addComponent(jTextFieldTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimer)
                    .addComponent(jTextFieldHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHour)
                    .addComponent(jTextFieldMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinutes))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonPublish)
                    .addComponent(jToggleButtonCancel))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalPointsActionPerformed

    private void jTextFieldHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHourActionPerformed

    private void jTextFieldTotalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTimeActionPerformed

    private void jTextFieldQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuestionsActionPerformed

    private void jToggleButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelActionPerformed
        JFrameTeacherHome teacherOverviewWindow = new JFrameTeacherHome(teacherRun);
        teacherOverviewWindow.setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCancelActionPerformed

    private void jToggleButtonPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPublishActionPerformed
        test.setPublished(true);
        JFrameTeacherHome teacherOverviewWindow = new JFrameTeacherHome(teacherRun);
        teacherOverviewWindow.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPublishActionPerformed

    private void jTextFieldAverageDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAverageDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAverageDifficultyActionPerformed

    private void jTextFieldClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClassActionPerformed

    private void jTextFieldTestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePublishTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePublishTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePublishTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePublishTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePublishTest(new TeacherRun(""), new Test()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAverageDifficulty;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelHour;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelQuestions;
    private javax.swing.JLabel jLabelTestName;
    private javax.swing.JLabel jLabelTestType;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JLabel jLabelTotalPoints;
    private javax.swing.JLabel jLabelTotalTime;
    private javax.swing.JTextField jTextFieldAverageDifficulty;
    private javax.swing.JTextField jTextFieldClass;
    private javax.swing.JTextField jTextFieldHour;
    private javax.swing.JTextField jTextFieldMinutes;
    private javax.swing.JTextField jTextFieldQuestions;
    private javax.swing.JTextField jTextFieldTestName;
    private javax.swing.JTextField jTextFieldTestType;
    private javax.swing.JTextField jTextFieldTotalPoints;
    private javax.swing.JTextField jTextFieldTotalTime;
    private javax.swing.JToggleButton jToggleButtonCancel;
    private javax.swing.JToggleButton jToggleButtonPublish;
    // End of variables declaration//GEN-END:variables
}
