/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.RunPackage.model.StudentRun;
import TestTool.model.RunPackage.view.JFrameStudentHome;
import TestTool.model.TestPackage.model.GradeTest;
import TestTool.model.TestPackage.model.Test;
import TestTool.model.UserPackage.Student;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dung Trinh
 */
public class JFrameTestResult extends javax.swing.JFrame {

    private StudentRun studentRun;
    private Test test;
    private DefaultTableModel model;
    //private StudentRun studentRun; 
    
    /**
     * Creates new form JFrameTestResult
     * @param Name of the student
     */
    public JFrameTestResult(StudentRun studentRun) {
        //change the actual data 
        this.studentRun = studentRun;
        this.test = studentRun.getCurrentTest();
       
                
        GradeTest grade = new GradeTest();
        grade.gradeTest(test);
        
        model = new DefaultTableModel();
        
        model.addColumn("Index");
        model.addColumn("Question");
        model.addColumn("Possible Point");
        model.addColumn("Your Point");
        
        for (int i = 0; i < test.size(); i++) {
            model.addRow(new Object[] {Integer.toString(i + 1),test.getQuestion(i).getText(), 
                                        test.getQuestion(i).getPointsWorth(), 
                                        test.getQuestion(i).getPointsEarned()});
        }
        
        
        initComponents();

        
        //done with the label and data processing
        jTextFieldClass.setText(test.getClassname());
        jTextFieldInstructor.setText(test.getInstructor());
        //grade
        jTextFieldStudentScore.setText(Integer.toString(studentRun.getScore(test)));
        jTextFieldTotalQuestions.setText(Integer.toString(test.size()));
        jTextFieldTotalScore.setText(Integer.toString(test.getPoint()));
        //student = studentRun.getStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTestResult = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelInsructor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTotalQuestions = new javax.swing.JLabel();
        jLabelTotalScore = new javax.swing.JLabel();
        jLabelStudentScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuestions = new javax.swing.JTable();
        jButtonContinue = new javax.swing.JButton();
        jTextFieldClass = new javax.swing.JTextField();
        jTextFieldInstructor = new javax.swing.JTextField();
        jTextFieldTotalQuestions = new javax.swing.JTextField();
        jTextFieldTotalScore = new javax.swing.JTextField();
        jTextFieldStudentScore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Test Result");

        jLabelTestResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTestResult.setText("Test Result");

        jLabelClass.setText("Class");

        jLabelInsructor.setText("Instructor");

        jLabelTotalQuestions.setText("Total Questions");

        jLabelTotalScore.setText("Total Score");

        jLabelStudentScore.setText("Your Score");

        jTableQuestions.setModel(model);
        jTableQuestions.setModel(model);
        jScrollPane1.setViewportView(jTableQuestions);
        if (jTableQuestions.getColumnModel().getColumnCount() > 0) {
            jTableQuestions.getColumnModel().getColumn(0).setPreferredWidth(4);
            jTableQuestions.getColumnModel().getColumn(0).setMaxWidth(4);
            jTableQuestions.getColumnModel().getColumn(0).setHeaderValue("#");
            jTableQuestions.getColumnModel().getColumn(1).setHeaderValue("Question");
            jTableQuestions.getColumnModel().getColumn(2).setHeaderValue("Total Points");
            jTableQuestions.getColumnModel().getColumn(3).setHeaderValue("Your Points");
        }

        jButtonContinue.setText("Continue");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        jTextFieldClass.setEditable(false);
        jTextFieldClass.setText("CPE 307");

        jTextFieldInstructor.setEditable(false);
        jTextFieldInstructor.setText("Fisher");

        jTextFieldTotalQuestions.setEditable(false);
        jTextFieldTotalQuestions.setText("10");
        jTextFieldTotalQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalQuestionsActionPerformed(evt);
            }
        });

        jTextFieldTotalScore.setEditable(false);
        jTextFieldTotalScore.setText("100");
        jTextFieldTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalScoreActionPerformed(evt);
            }
        });

        jTextFieldStudentScore.setEditable(false);
        jTextFieldStudentScore.setText("90");
        jTextFieldStudentScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClass)
                    .addComponent(jLabelInsructor))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButtonContinue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotalScore)
                                .addGap(49, 49, 49)
                                .addComponent(jTextFieldTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotalQuestions)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldTotalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStudentScore)
                                .addGap(52, 52, 52)
                                .addComponent(jTextFieldStudentScore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClass)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsructor)
                    .addComponent(jTextFieldInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalQuestions)
                    .addComponent(jTextFieldTotalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalScore)
                    .addComponent(jTextFieldTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStudentScore)
                    .addComponent(jTextFieldStudentScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonContinue)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        System.out.println("Call JFrameStudentHome");
        JFrameStudentHome studentHome = new JFrameStudentHome(studentRun);
        
        //Remove the test from the taken test list
        //Remove the test from the actual date object
        //Checking the number of test
        
        int testLeft = this.studentRun.removeTest(test);
        /*
            if testLeft == 0
                //do something
            else
                go back to home
        */
        
        
        
        //Change the original studentHome
        studentHome = new JFrameStudentHome(this.studentRun) ;
        studentHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jTextFieldTotalQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalQuestionsActionPerformed

    private void jTextFieldTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalScoreActionPerformed

    private void jTextFieldStudentScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestResult(new StudentRun("")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelInsructor;
    private javax.swing.JLabel jLabelStudentScore;
    private javax.swing.JLabel jLabelTestResult;
    private javax.swing.JLabel jLabelTotalQuestions;
    private javax.swing.JLabel jLabelTotalScore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableQuestions;
    private javax.swing.JTextField jTextFieldClass;
    private javax.swing.JTextField jTextFieldInstructor;
    private javax.swing.JTextField jTextFieldStudentScore;
    private javax.swing.JTextField jTextFieldTotalQuestions;
    private javax.swing.JTextField jTextFieldTotalScore;
    // End of variables declaration//GEN-END:variables
}
