/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.QuestionPackage.model.MultipleChoiceQuestion;
import TestTool.model.QuestionPackage.model.Question;
import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.TestPackage.model.GradeTest;
import TestTool.model.TestPackage.model.Test;
import TestTool.model.UserPackage.Student;
import TestTool.model.UserPackage.Teacher;

/**
 *
 * @author Zach
 */
public class JFrameGradeQuestion extends javax.swing.JFrame {

    TeacherRun teacherRun;
    Teacher teacher;
    Student student;
    Test test;
    int index = 0;
    /**
     * Creates new form JFrameGradeQuestion
     */
    public JFrameGradeQuestion(TeacherRun teacherRun, Test test, Student student) {
        this.teacherRun = teacherRun;
        this.teacher = teacherRun.getTeacher();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGradeQuestion = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jLabelQuestionText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuestionText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAnswerText = new javax.swing.JTextArea();
        jLabelAnswer = new javax.swing.JLabel();
        jLabelPoints = new javax.swing.JLabel();
        jTextFieldPoints = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaComments = new javax.swing.JTextArea();
        jTextFieldCurrentNumber = new javax.swing.JTextField();
        jLabelDivisor = new javax.swing.JLabel();
        jTextFieldTotalNumber = new javax.swing.JTextField();
        jButtonPrevious = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelPoints1 = new javax.swing.JLabel();
        jLabelPointDivisor = new javax.swing.JLabel();
        jTextFieldPointsWorth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Grade Question");

        jLabelGradeQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGradeQuestion.setText("Grade Question");

        jTextFieldStudentID.setEditable(false);
        jTextFieldStudentID.setText(student.getStudentName());

        jLabelQuestionText.setText("Question Text:");

        jTextAreaQuestionText.setEditable(false);
        jTextAreaQuestionText.setColumns(20);
        jTextAreaQuestionText.setRows(5);
        jTextAreaQuestionText.setText(test.getQuestion(0).getText()
        );
        jScrollPane1.setViewportView(jTextAreaQuestionText);

        jTextAreaAnswerText.setEditable(false);
        jTextAreaAnswerText.setColumns(20);
        jTextAreaAnswerText.setRows(5);
        jTextAreaAnswerText.setText(test.getQuestion(0).getText());
        jScrollPane2.setViewportView(jTextAreaAnswerText);

        jLabelAnswer.setText("Answer:");

        jLabelPoints.setText("Points:");

        jTextFieldPoints.setText("" + test.getQuestion(0).getPointsEarned());
        jTextFieldPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPointsActionPerformed(evt);
            }
        });

        jTextAreaComments.setColumns(20);
        jTextAreaComments.setRows(5);
        jTextAreaComments.setText(test.getQuestion(0).getTeacherComment());
        jScrollPane3.setViewportView(jTextAreaComments);

        jTextFieldCurrentNumber.setEditable(false);
        jTextFieldCurrentNumber.setText("" + index);
        jTextFieldCurrentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCurrentNumberActionPerformed(evt);
            }
        });

        jLabelDivisor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDivisor.setText("/");

        jTextFieldTotalNumber.setEditable(false);
        jTextFieldTotalNumber.setText("" + test.size());
        jTextFieldTotalNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalNumberActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabelPoints1.setText("Comments:");

        jLabelPointDivisor.setText("/");

        jTextFieldPointsWorth.setEditable(false);
        jTextFieldPointsWorth.setText("" + test.getQuestion(0).getPointsWorth());
        jTextFieldPointsWorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPointsWorthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabelGradeQuestion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuestionText)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnswer))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPointDivisor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPointsWorth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPoints1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonQuit)
                                .addContainerGap(19, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPrevious)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldCurrentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDivisor, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTotalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNext)
                                        .addContainerGap(16, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGradeQuestion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonQuit)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelQuestionText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPoints)
                            .addComponent(jTextFieldPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPointDivisor)
                            .addComponent(jTextFieldPointsWorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPoints1)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCurrentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDivisor)
                            .addComponent(jTextFieldTotalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPrevious)
                            .addComponent(jButtonNext))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPointsActionPerformed

    private void jTextFieldCurrentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCurrentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCurrentNumberActionPerformed

    private void jTextFieldTotalNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalNumberActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        test.getQuestion(index).setTeacherComment(jTextAreaComments.getText());
        // test.getQuestion(0). need a value that isn't points worth.
        JFrameGradeQuestionBank gradeQuestionBankWindow = new JFrameGradeQuestionBank(teacherRun, test);
        gradeQuestionBankWindow.setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jTextFieldPointsWorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPointsWorthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPointsWorthActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
    test.getQuestion(index).setTeacherComment(jTextAreaComments.getText());
    test.getQuestion(index).setPointsEarned(Integer.parseInt(jTextFieldPoints.getText()));
    if (index < test.questions.size()) {
        index++;
    }
    jTextAreaQuestionText.setText(test.questions.get(index).getText());
    jTextAreaAnswerText.setText(GradeTest.getStudentAnswer(test.questions.get(index)));
    jTextAreaComments.setText(test.questions.get(index).getTeacherComment());
    jTextFieldCurrentNumber.setText("" + (index + 1));
    jTextFieldPointsWorth.setText("" + test.questions.get(index).getPointsWorth());
    jTextFieldPoints.setText("" + test.questions.get(index).getPointsEarned());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
    test.getQuestion(index).setTeacherComment(jTextAreaComments.getText());
    test.getQuestion(index).setPointsEarned(Integer.parseInt(jTextFieldPoints.getText()));
    if (index != 0) {
        index--;
    }
    jTextAreaQuestionText.setText(test.questions.get(index).getText());
    jTextAreaAnswerText.setText(GradeTest.getStudentAnswer(test.questions.get(index)));
    jTextAreaComments.setText(test.questions.get(index).getTeacherComment());
    jTextFieldCurrentNumber.setText("" + (index + 1));
    jTextFieldPointsWorth.setText("" + test.questions.get(index).getPointsWorth());
    jTextFieldPoints.setText("" + test.questions.get(index).getPointsEarned());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGradeQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGradeQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGradeQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGradeQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGradeQuestion(new TeacherRun(""), new Test(), new Student("", "")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelDivisor;
    private javax.swing.JLabel jLabelGradeQuestion;
    private javax.swing.JLabel jLabelPointDivisor;
    private javax.swing.JLabel jLabelPoints;
    private javax.swing.JLabel jLabelPoints1;
    private javax.swing.JLabel jLabelQuestionText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaAnswerText;
    private javax.swing.JTextArea jTextAreaComments;
    private javax.swing.JTextArea jTextAreaQuestionText;
    private javax.swing.JTextField jTextFieldCurrentNumber;
    private javax.swing.JTextField jTextFieldPoints;
    private javax.swing.JTextField jTextFieldPointsWorth;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldTotalNumber;
    // End of variables declaration//GEN-END:variables
}
