/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.TestPackage.model.GenerateTest;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Zach
 */
public class JFrameAutoGenerate extends javax.swing.JFrame {

    TeacherRun teacherRun;
    JFrameCreateTest createWindow;
    /**
     * Creates new form JFrameAutoGenerate
     * @param teacherRun
     * @param createWindow
     */
    public JFrameAutoGenerate(TeacherRun teacherRun, JFrameCreateTest createWindow) {
        this.teacherRun = teacherRun;
        this.createWindow = createWindow;
        initComponents();
    }
    
    public JFrameAutoGenerate() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTotalTime = new javax.swing.JLabel();
        jTextFieldTotalTime = new javax.swing.JTextField();
        jLabelQuestions = new javax.swing.JLabel();
        jTextFieldQuestions = new javax.swing.JTextField();
        jLabelAverageDifficulty = new javax.swing.JLabel();
        jTextFieldAverageDifficulty = new javax.swing.JTextField();
        jLabelTotalPoints = new javax.swing.JLabel();
        jTextFieldTotalPoints = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jToggleButtonBack = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Auto-Generate");

        jLabelTotalTime.setText("Total Time:");

        jTextFieldTotalTime.setText("7");
        jTextFieldTotalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTimeActionPerformed(evt);
            }
        });

        jLabelQuestions.setText("Questions:");

        jTextFieldQuestions.setText("2");
        jTextFieldQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuestionsActionPerformed(evt);
            }
        });

        jLabelAverageDifficulty.setText("Average Difficulty:");

        jTextFieldAverageDifficulty.setText("4");
        jTextFieldAverageDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAverageDifficultyActionPerformed(evt);
            }
        });

        jLabelTotalPoints.setText("Total Points:");

        jTextFieldTotalPoints.setText("8");
        jTextFieldTotalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalPointsActionPerformed(evt);
            }
        });

        jButtonNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jToggleButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonBack.setText("Back");
        jToggleButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAverageDifficulty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButtonBack)
                                    .addComponent(jLabelTotalPoints))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTotalTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonNext)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelQuestions)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAverageDifficulty)
                    .addComponent(jTextFieldAverageDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalTime)
                    .addComponent(jTextFieldTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalPoints)
                    .addComponent(jTextFieldTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuestions)
                    .addComponent(jTextFieldQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonBack)
                    .addComponent(jButtonNext))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTimeActionPerformed

    private void jTextFieldQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuestionsActionPerformed

    private void jTextFieldAverageDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAverageDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAverageDifficultyActionPerformed

    private void jTextFieldTotalPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalPointsActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        //JFrameCreateTestQuestionBank createTestQuestionBankWindow = new JFrameCreateTestQuestionBank(teacherRun, autoTest);
        //createTestQuestionBankWindow.setVisible(true);
        Random randomGen = new Random();
        int randomNum = randomGen.nextInt(5); 
        ArrayList<Integer> indices = new ArrayList<>(); //arraylist to hold indices of test bank questions
        while (indices.size() < Integer.parseInt(jTextFieldQuestions.getText()) && indices.size() < 5) {
            if (!indices.contains(randomNum)) {
               indices.add(randomNum);
               System.out.println("num added");
            }
            randomNum = randomGen.nextInt(5);
            System.out.println("Num generated");
        }
        
        new GenerateTest(teacherRun, createWindow, indices);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jToggleButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBackActionPerformed
        JFrameCreateTest createWindow = new JFrameCreateTest(teacherRun);
        createWindow.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAutoGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAutoGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAutoGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAutoGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAutoGenerate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAverageDifficulty;
    private javax.swing.JLabel jLabelQuestions;
    private javax.swing.JLabel jLabelTotalPoints;
    private javax.swing.JLabel jLabelTotalTime;
    private javax.swing.JTextField jTextFieldAverageDifficulty;
    private javax.swing.JTextField jTextFieldQuestions;
    private javax.swing.JTextField jTextFieldTotalPoints;
    private javax.swing.JTextField jTextFieldTotalTime;
    private javax.swing.JToggleButton jToggleButtonBack;
    // End of variables declaration//GEN-END:variables
}
