/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.TestPackage.view;

import TestTool.model.RunPackage.model.StudentRun;
import TestTool.model.RunPackage.view.JFrameStudentHome;
import TestTool.model.TestPackage.model.Test;
import TestTool.model.UserPackage.Student;

/**
 *
 * @author Dung Trinh
 */
public class JFrameTestInfo extends javax.swing.JFrame {

    private StudentRun studentRun;
    private Student student;
    private Test test;
    private int testIndex;
    
    /**
     * Creates new form JFrameTestInfo
     */
    public JFrameTestInfo(StudentRun studentRun, int testIndex) {
        this.studentRun = studentRun; 
        this.student = studentRun.getStudent();
        this.testIndex = testIndex;
        
        test = student.getAvailableTest().get(testIndex);
        
        //Netbean GUI Initialization
        initComponents();

        //Set all text field
        jTextFieldClass.setText(test.getClassname());
        jTextFieldDifficulty.setText(test.getDifficulty() + "");
        jTextFieldInstructor.setText(test.getInstructor());
        jTextFieldTestType.setText("In class");
        jTextFieldTime.setText(Double.toString(test.getTestTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jLabelInstructor = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelTestType = new javax.swing.JLabel();
        jLabelDifficulty = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelConfirmation = new javax.swing.JLabel();
        jTextFieldInstructor = new javax.swing.JTextField();
        jTextFieldClass = new javax.swing.JTextField();
        jTextFieldTestType = new javax.swing.JTextField();
        jTextFieldDifficulty = new javax.swing.JTextField();
        jLabelMinutes = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Test Info");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonAccept.setText("Accept");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });

        jLabelInstructor.setText("Instructor");

        jLabelClass.setText("Class");

        jLabelTestType.setText("Test-type");

        jLabelDifficulty.setText("Difficulty");

        jLabelTime.setText("Time");

        jLabelConfirmation.setText("Do you want to start the test?");

        jTextFieldInstructor.setEditable(false);
        jTextFieldInstructor.setText("Fisher");
        jTextFieldInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstructorActionPerformed(evt);
            }
        });

        jTextFieldClass.setEditable(false);
        jTextFieldClass.setText("CPE307");
        jTextFieldClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClassActionPerformed(evt);
            }
        });

        jTextFieldTestType.setEditable(false);
        jTextFieldTestType.setText("Practice");
        jTextFieldTestType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestTypeActionPerformed(evt);
            }
        });

        jTextFieldDifficulty.setEditable(false);
        jTextFieldDifficulty.setText("7");
        jTextFieldDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDifficultyActionPerformed(evt);
            }
        });

        jLabelMinutes.setText("Min");

        jTextFieldTime.setEditable(false);
        jTextFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstructor)
                                    .addComponent(jLabelClass))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(jTextFieldInstructor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTime)
                                    .addComponent(jLabelDifficulty)
                                    .addComponent(jLabelTestType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTestType)
                                    .addComponent(jTextFieldDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTime))))
                        .addGap(1, 1, 1)
                        .addComponent(jLabelMinutes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addGap(69, 69, 69)
                                .addComponent(jButtonAccept)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInstructor)
                    .addComponent(jTextFieldInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClass)
                    .addComponent(jTextFieldClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTestType)
                    .addComponent(jTextFieldTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDifficulty)
                    .addComponent(jTextFieldDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTime)
                    .addComponent(jLabelMinutes)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabelConfirmation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonAccept))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Confirm to take test button 
     * @param evt 
     */
    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        System.out.println("Take test. Call JFrameTestTaking");
        //why does this fail ?
        studentRun.setCurrentTest(this.testIndex);
        System.out.println("In test info " + studentRun.getCurrentTest().size());
        JFrameTestTaking newJFrameTestingExample = new JFrameTestTaking(studentRun);
        newJFrameTestingExample.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    /**
     * Go back to the previous screen 
     * @param evt 
     */
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        System.out.println("Back. Call JFrameStudentHome");
        JFrameStudentHome newJFrameStudentHome = new JFrameStudentHome(new StudentRun(""));
        newJFrameStudentHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed
    
    private void jTextFieldInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstructorActionPerformed
       //Do nothing
    }//GEN-LAST:event_jTextFieldInstructorActionPerformed

    private void jTextFieldClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClassActionPerformed

    private void jTextFieldTestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestTypeActionPerformed
    
    private void jTextFieldDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDifficultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDifficultyActionPerformed

    private void jTextFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Default to run
                new JFrameTestInfo(new StudentRun(""),1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelConfirmation;
    private javax.swing.JLabel jLabelDifficulty;
    private javax.swing.JLabel jLabelInstructor;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelTestType;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JTextField jTextFieldClass;
    private javax.swing.JTextField jTextFieldDifficulty;
    private javax.swing.JTextField jTextFieldInstructor;
    private javax.swing.JTextField jTextFieldTestType;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables
}
