/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.model.QuestionPackage.view;

import TestTool.model.RunPackage.model.TeacherRun;

/**
 *
 * @author Zach
 */
public class JFrameFilterQuestions extends javax.swing.JFrame {

    TeacherRun teacherRun;
    /**
     * Creates new form JFrameFilterQuestions
     */
    public JFrameFilterQuestions(TeacherRun teacherRun) {
        this.teacherRun = teacherRun;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFilterQuestions = new javax.swing.JLabel();
        jLabelQuestionText = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelQuestionType = new javax.swing.JLabel();
        jLabelDifficulty = new javax.swing.JLabel();
        jLabelPointValue = new javax.swing.JLabel();
        jTextFieldQuestionText = new javax.swing.JTextField();
        jComboBoxClass = new javax.swing.JComboBox();
        jComboBoxQuestionType = new javax.swing.JComboBox();
        jLabelDifficultyLow = new javax.swing.JLabel();
        jLabelDifficultyHigh = new javax.swing.JLabel();
        jTextFieldDifficultyLow = new javax.swing.JTextField();
        jTextFieldDifficultyHigh = new javax.swing.JTextField();
        jLabelPointLow = new javax.swing.JLabel();
        jLabelPointHigh = new javax.swing.JLabel();
        jTextFieldPointLow = new javax.swing.JTextField();
        jTextFieldPointHigh = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Filter Questions");

        jLabelFilterQuestions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFilterQuestions.setText("Filter Questions");

        jLabelQuestionText.setText("Question Text:");

        jLabelClass.setText("Class:");

        jLabelQuestionType.setText("Question Type:");

        jLabelDifficulty.setText("Difficulty:");

        jLabelPointValue.setText("Point Value:");

        jTextFieldQuestionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuestionTextActionPerformed(evt);
            }
        });

        jComboBoxClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "307", "315" }));

        jComboBoxQuestionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mutiple Choice", "Matching", "Free Answer", "True False" }));

        jLabelDifficultyLow.setText("Low:");

        jLabelDifficultyHigh.setText("High:");

        jTextFieldDifficultyLow.setText("0");
        jTextFieldDifficultyLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDifficultyLowActionPerformed(evt);
            }
        });

        jTextFieldDifficultyHigh.setText("0");
        jTextFieldDifficultyHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDifficultyHighActionPerformed(evt);
            }
        });

        jLabelPointLow.setText("Low:");

        jLabelPointHigh.setText("High:");

        jTextFieldPointLow.setText("0");
        jTextFieldPointLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPointLowActionPerformed(evt);
            }
        });

        jTextFieldPointHigh.setText("0");
        jTextFieldPointHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPointHighActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFilterQuestions)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQuestionText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPointValue)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelPointLow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPointLow, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButtonCancel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPointHigh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPointHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSubmit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuestionType)
                            .addComponent(jLabelClass)
                            .addComponent(jLabelDifficulty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDifficultyLow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDifficultyLow, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDifficultyHigh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDifficultyHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFilterQuestions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestionText)
                    .addComponent(jTextFieldQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClass)
                    .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestionType)
                    .addComponent(jComboBoxQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDifficulty)
                    .addComponent(jLabelDifficultyLow)
                    .addComponent(jLabelDifficultyHigh)
                    .addComponent(jTextFieldDifficultyLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDifficultyHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPointValue)
                    .addComponent(jLabelPointLow)
                    .addComponent(jLabelPointHigh)
                    .addComponent(jTextFieldPointLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPointHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSubmit))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDifficultyLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDifficultyLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDifficultyLowActionPerformed

    private void jTextFieldDifficultyHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDifficultyHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDifficultyHighActionPerformed

    private void jTextFieldPointLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPointLowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPointLowActionPerformed

    private void jTextFieldPointHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPointHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPointHighActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        JFrameQuestionBank questionBankWindow = new JFrameQuestionBank(teacherRun);
        questionBankWindow.setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        JFrameQuestionBank questionBankWindow = new JFrameQuestionBank(teacherRun);
        questionBankWindow.setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextFieldQuestionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuestionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuestionTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFilterQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFilterQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFilterQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFilterQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFilterQuestions(new TeacherRun("")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxClass;
    private javax.swing.JComboBox jComboBoxQuestionType;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelDifficulty;
    private javax.swing.JLabel jLabelDifficultyHigh;
    private javax.swing.JLabel jLabelDifficultyLow;
    private javax.swing.JLabel jLabelFilterQuestions;
    private javax.swing.JLabel jLabelPointHigh;
    private javax.swing.JLabel jLabelPointLow;
    private javax.swing.JLabel jLabelPointValue;
    private javax.swing.JLabel jLabelQuestionText;
    private javax.swing.JLabel jLabelQuestionType;
    private javax.swing.JTextField jTextFieldDifficultyHigh;
    private javax.swing.JTextField jTextFieldDifficultyLow;
    private javax.swing.JTextField jTextFieldPointHigh;
    private javax.swing.JTextField jTextFieldPointLow;
    private javax.swing.JTextField jTextFieldQuestionText;
    // End of variables declaration//GEN-END:variables
}
