/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestTool.view.WindowPackage;

import TestTool.model.RunPackage.model.StudentRun;
import TestTool.model.RunPackage.model.TeacherRun;
import TestTool.model.RunPackage.view.JFrameStudentHome;
import TestTool.model.RunPackage.view.JFrameTeacherHome;
import TestTool.model.UserPackage.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author Dung Trinh
 */
public class JFrameLogin extends javax.swing.JFrame {

    private StudentRun studentRun;
    private TeacherRun teacherRun;
    private ArrayList<Student> studentList;
    private ArrayList<Teacher> teacherList;

    /**
     * Creates new form LoginJFrame
     */
    public JFrameLogin() {
        initComponents();
        studentList = UserDatabase.getStudentDB();
        teacherList = UserDatabase.getTeacherDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserName = new javax.swing.JLabel();
        JLabelPassword = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jLabelGalactestLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galactest - Login");

        jLabelUserName.setText("Cal Poly User Email");

        JLabelPassword.setText("Password");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        jLabelGalactestLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelGalactestLogin.setText("Galactest Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName)
                            .addComponent(JLabelPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUser)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabelGalactestLogin)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGalactestLogin)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Create jFrame Window for appropiate user");
        boolean match = false;
        boolean nameMatch = false;
        
        //can check by using the static to get the data
        //If student.contain(text) == true
        //will chenge when the data is complete
        //studentRun = new StudentRun(jTextFieldUser.getText());
        
        for (Student s: studentList) {
            if (jTextFieldUser.getText().equals(s.getName())) {
                nameMatch = true;
                if (jTextFieldPassword.getText().equals(s.getPassword())) {
                    //need id
                    studentRun = new StudentRun(jTextFieldUser.getText());
                    match = true;
                    this.setVisible(false);
                }
            }
        }
        
        for (Teacher t: teacherList) {
            if (jTextFieldUser.getText().equals(t.getName())) {   
                nameMatch = true;
                if (jTextFieldPassword.getText().equals(t.getPassword())) {
                    //need id
                    teacherRun = new TeacherRun(jTextFieldUser.getText());
                    match = true;
                    this.setVisible(false);
                }
            }
        }
        if (!match && !nameMatch && jTextFieldUser.getText().charAt(0) == 't') {
            Teacher newTeacher = new Teacher(jTextFieldUser.getText(), 
                jTextFieldPassword.getText());
            System.out.println("You've created a new Teacher account, " 
                    + newTeacher.getName() + "!");
            UserDatabase.addTeacher(newTeacher);
            teacherList = UserDatabase.getTeacherDB();
            teacherRun = new TeacherRun(jTextFieldUser.getText());
            this.setVisible(false);
        }
        else if (!match && !nameMatch && jTextFieldUser.getText().charAt(0) == 's') {
            Student newStudent = new Student(jTextFieldUser.getText(), 
                jTextFieldPassword.getText());
            System.out.println("You've created a new Student account, " 
                    + newStudent.getName() + "!");
            UserDatabase.addStudent(newStudent);
            studentList = UserDatabase.getStudentDB();
            studentRun = new StudentRun(jTextFieldUser.getText());
            this.setVisible(false);
        }
        else if (!nameMatch || !match) {
            System.out.println("Invalid entry");
        }
    }

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelPassword;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelGalactestLogin;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
